# General server settings
server:
    host: localhost
    port: 7777
    debug: True

# WES service info settings
service_info:
    contact_info: https://github.com/elixir-europe/WES-ELIXIR
    auth_instructions_url: https://www.elixir-europe.org/services/compute/aai
    supported_file_system_protocols:
        - http
    supported_wes_versions:
        - 0.3.0
    workflow_type_versions:
        CWL:
            workflow_type_version:
                - v1.0
    workflow_engine_versions:
        cwl-tes: 0.2.0
    default_workflow_engine_parameters:
        - type: string
          default_value: "abc"
        - type: int
          default_value: "5"
    tags:
        known_tes_endpoints: ["https://tes-dev.tsi.ebi.ac.uk/"]
        some_param_2: something_else
        some_param_3: another_thing
        some_param_4: yet_another_thing
        some_param_5: and_yet_another_thing

# Location of OpenAPI specs
openapi:
    path: 'openapi'
    yaml_specs: 'ga4gh.wes.0.3.0.openapi.yaml'

# Database settings
database:
    host: 'localhost'
    port: 27017
    name: wes-elixir-db
    run_id:
        length: 6
        charset: string.ascii_uppercase + string.digits

# Endpoint parameters
api_endpoints:
    default_page_size: 10

# TES server
tes:
    url: https://tes-dev.tsi.ebi.ac.uk/
