# General server/service settings
server:
    port: 80
    debug: False
    environment: production
    use_reloader: False

# Security settings
security:
    authorization_required: True

# Database settings
database:
    host: 'mongo'

# Storage
storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'

# Celery task queue
celery:
    broker_url: 'pyamqp://rabbit:5672//'

# OpenAPI specs

# WES service info settings

# TES server
