# General server/service settings
server:
    port: 8080

# Security settings
security:
    authorization_required: False

# Database settings
database:
    host: 'mongo'
    name: wes-elixir-db-dev

# Storage
storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'

# Celery task queue
celery:
    broker_host: 'rabbit'
    broker_port: 5672

# OpenAPI specs

# WES service info settings

# TES server
