# General server/service settings
server:
    host: localhost
    port: 7777
    debug: True
    environment: development
    testing: False
    use_reloader: True

# Security settings
security:
    authorization_required: True
    jwt:
        algorithm: RS256
        public_key: |-
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33TqqLR3eeUmDtHS89qF
            3p4MP7Wfqt2Zjj3lZjLjjCGDvwr9cJNlNDiuKboODgUiT4ZdPWbOiMAfDcDzlOxA
            04DDnEFGAf+kDQiNSe2ZtqC7bnIc8+KSG/qOGQIVaay4Ucr6ovDkykO5Hxn7OU7s
            Jp9TP9H0JH8zMQA6YzijYH9LsupTerrY3U6zyihVEDXXOv08vBHk50BMFJbE9iwF
            wnxCsU5+UZUZYw87Uu0n4LPFS9BT8tUIvAfnRXIEWCha3KbFWmdZQZlyrFw0buUE
            f0YN3/Q0auBkdbDR/ES2PbgKTJdkjc/rEeM0TxvOUf7HuUNOhrtAVEN1D5uuxE1W
            SwIDAQAB
            -----END PUBLIC KEY-----
        header_name: Authorization
        token_prefix: Bearer
        identity_claim: sub
        user_claims:
            type: access
            fresh: non-fresh

# Database settings
database:
    host: 'localhost'
    port: 27017
    name: wes-elixir-db
    run_id:
        length: 6
        charset: string.ascii_uppercase + string.digits

# Storage
storage:
    permanent_dir: 'tests/output'
    tmp_dir: 'tests/tmp'
    remote_storage_url: 'ftp://ftp-private.ebi.ac.uk/upload/foivos'

# Celery task queuer
celery:
    broker_url: 'pyamqp://localhost:5672//'
    result_backend: 'rpc://'
    include:
        - wes_elixir.ga4gh.wes.utils_bg_tasks
    monitor:
        timeout: 0.1

# OpenAPI specs
api:
    specs: 
        - path: '20180830.74fd916da3.workflow_execution_service.swagger.yaml'
          strict_validation: True
          validate_responses: True
          swagger_ui: True
          swagger_json: True

# WES service info settings
service_info:
    contact_info: 'https://github.com/elixir-europe/WES-ELIXIR'
    auth_instructions_url: 'https://www.elixir-europe.org/services/compute/aai'
    supported_file_system_protocols:
        - http
    supported_wes_versions:
        - 0.3.0
    workflow_type_versions:
        CWL:
            workflow_type_version:
                - v1.0
    workflow_engine_versions:
        cwl-tes: 0.2.0
    default_workflow_engine_parameters:
        - type: string
          default_value: some_string
        - type: int
          default_value: '5'
    tags:
        known_tes_endpoints: 'https://tes-dev.tsi.ebi.ac.uk/'
        wes_elixir_version: 0.7.0

# Endpoint parameters
api_endpoints:
    default_page_size: 10

# TES server
tes:
    url: 'https://tes-dev.tsi.ebi.ac.uk/'