# General server/service settings
server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: True

# Security settings
security:
    authorization_required: False
    jwt:
        algorithms:
          - RS256
        claim_identity: sub
        claim_issuer: iss
        claim_key_id: kid
        header_name: Authorization
        token_prefix: Bearer
        validation_methods:
          - userinfo
          - public_key
        validation_checks: any  # 'any' or 'all'

# Database settings
database:
    host: 'localhost'
    port: 27017
    name: wes-elixir-db
    run_id:
        length: 6
        charset: string.ascii_uppercase + string.digits

# Storage
storage:
    permanent_dir: 'tests/output'
    tmp_dir: 'tests/tmp'
    remote_storage_url: 'ftp://ftp-private.ebi.ac.uk/upload/foivos'

# Celery task queue
celery:
    broker_host: 'localhost'
    broker_port: 5672
    result_backend: 'rpc://'
    include:
        - wes_elixir.tasks.tasks.run_workflow
        - wes_elixir.tasks.tasks.cancel_run
    monitor:
        timeout: 0.1
    message_maxsize: 16777216

# OpenAPI specs
api:
    specs:
        - name: 'WES'
          path: '20181023.c5406f1-v1-0-0.workflow_execution_service.swagger.yaml'
          strict_validation: True
          validate_responses: True
          swagger_ui: True
          swagger_json: True
          base_path: False
        - name: 'stdout_stderr'
          path: 'schema.stdout_stderr.openapi.yaml'
          strict_validation: True
          validate_responses: True
          swagger_ui: True
          swagger_json: True
          base_path: '/wes-elixir/v1'
    general_params:
        time_format: "%Y-%m-%dT%H:%M:%SZ"
    endpoint_params:
        default_page_size: 5
        timeout_cancel_run: 60
        timeout_run_workflow: Null

# WES service info settings
service_info:
    contact_info: 'https://github.com/elixir-europe/WES-ELIXIR'
    auth_instructions_url: 'https://www.elixir-europe.org/services/compute/aai'
    supported_file_system_protocols:
        - http
    supported_wes_versions:
        - 0.3.0
    workflow_type_versions:
        CWL:
            workflow_type_version:
                - v1.0
    workflow_engine_versions:
        cwl-tes: 0.2.0
    default_workflow_engine_parameters:
        - type: string
          default_value: some_string
        - type: int
          default_value: '5'
    tags:
        known_tes_endpoints: 'https://tes.tsi.ebi.ac.uk/|https://tes-dev.tsi.ebi.ac.uk/|https://csc-tesk.c03.k8s-popup.csc.fi/|https://tesk.c01.k8s-popup.csc.fi/'
        wes_elixir_version: 0.14.0

# TES server
tes:
    url: 'https://csc-tesk.c03.k8s-popup.csc.fi/'
    timeout: 5
    get_logs:
        url_root: 'v1/tasks/'
        query_params: '?view=FULL'
